### ISSUE TITLE
проблем с тестовете на контролерите

### ISSUE THREAD

**Issue by DesislavaGetova-Petrova** [luchob/softuni-music-db#34]
Здравей Лъчо, срам не срам отново ще помоля да погледнеш какво друго бъркам, че не нито един Integration test не минава. Мисля че оправих нещата които препоръча вчера, но въпреки това ми дава грешка : " java.lang.IllegalStateException: Failed to load ApplicationContext". Например за LessonControlerTest.
https://github.com/DesislavaGetova-Petrova/TheProject/tree/master/src/test/java/desico/project/web

**Comment by luchob** [comment]
Здрасти :-)

Да, не може да вдигне контекста, заради това:
```
    jpa:
        #For H2 Database
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
```
Задала си му едновременно MySQL и H2 диалект, като ти трябва последния:

```
    jpa:
        #For H2 Database
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
```

Поздрави,
Л.
